pub const TEMPL_DEFAULT_DATETIME_FORMAT: &str = "TEMPL_DEFAULT_DATETIME_FORMAT";
pub const TEMPL_DEFAULT_DATE_FORMAT: &str = "TEMPL_DEFAULT_DATE_FORMAT";
pub const CHROMIUM_SANDBOXED: &str = "CHROMIUM_SANDBOXED";
